services:
  app:
    build: ./
    container_name: incident-map
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - MONGO_URI=mongodb://root:root@mongodb:27017/incident-map?authSource=admin
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

volumes:
  node_modules:
  mongodb:
